project:
  type: website
  output-dir: _site

website:
  title: "Baltic Cod Predation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maps.qmd
        text: Prediction Maps
      - href: results.qmd
        text: Results

format:
  html:
    theme: cosmo
    toc: true
